# Generated by Django 2.2.16 on 2020-11-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zapato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.TextField(max_length=50)),
                ('material', models.TextField(max_length=50)),
                ('color', models.TextField(max_length=50)),
                ('talla', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to='Galeria', verbose_name='Imagen')),
            ],
        ),
    ]
