# Generated by Django 2.2.16 on 2020-11-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapato',
            name='image',
            field=models.ImageField(null='false', upload_to='Galeria', verbose_name='Imagen'),
        ),
    ]
